# Generated by Django 5.2.16 on 2026-07-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionrequirement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='proficiencyscale',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skillrating',
            options={'ordering': ['-rated_at']},
        ),
    ]
