# Generated by Django 5.2.16 on 2026-07-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_positionrequirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiencyscale',
            name='level_descriptions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
