# Generated by Django 5.2.16 on 2026-07-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_proficiencyscale_level_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'skill categories'},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
