# Generated by Django 5.2.16 on 2026-07-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_options_alter_skillcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proficiencyscale',
            options={},
        ),
        migrations.RemoveField(
            model_name='proficiencyscale',
            name='level_descriptions',
        ),
        migrations.RemoveField(
            model_name='proficiencyscale',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='level_descriptions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
