# Generated by Django 5.2.16 on 2026-07-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('validity_period_months', models.IntegerField(blank=True, null=True)),
                ('related_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='certifications.certification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='people.employee')),
            ],
        ),
    ]
