# Generated by Django 5.2.16 on 2026-07-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employeecertification',
            options={'ordering': ['-issued_at']},
        ),
    ]
