# Generated by Django 5.2.16 on 2026-07-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['department', 'id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level', 'title']},
        ),
    ]
